### ISSUE TITLE
Անվանափոխության հայց

### ISSUE THREAD

**Issue by hisusqristos** [aniordyan/family#1]
«bazmazavak» ոնց ա հնչում քո ականջին? կլինի aniordyan/bazmazavak

սա ձեզ 🌹

**Comment by aniordyan** [comment]
ահահա հրաշալի է հնչում
իրականում պատկերացում չունեմ խի եմ էս ռեփոն բացել

**Comment by hisusqristos** [comment]
Դու շատ ունես խառը ռեպոներ բացած,խաածիչնի (😝) տրամադրություն ա տալիս, վսյո ժե պրեզենտաբելնիության հաշվին։ Հավես լինի մի հատ նայի (հավաքարարի աչքով!!)

![image](https://github.com/aniordyan/family/assets/85686319/fb2f6616-a97b-4e36-9841-0b1a04d1aa4e)
